In [2]:
import pandas as pd
import datetime
from pathlib import Path
from tadpole_algorithms.models import BenchmarkLastVisit

train_set_path = Path("data/TADPOLE_D1_D2.csv")
test_set_path = Path("data/tadpole_test_set.csv")

train_df = pd.read_csv(train_set_path)
test_set_df = pd.read_csv(test_set_path)


model = BenchmarkLastVisit()
model.train(train_df)

forecast_df = model.predict(test_set_df)
print(forecast_df)

[]
       RID  month Forecast Date  CN relative probability  \
0      2.0      1    02/02/2013                      1.0   
1      8.0      1    06/03/2007                      1.0   
2     15.0      1    07/04/2006                      1.0   
3     21.0      1    08/10/2005                      1.0   
4     23.0      1    09/02/2008                      1.0   
..     ...    ...           ...                      ...   
64   408.0    119    28/02/2021                      0.0   
65   413.0    119    30/06/2018                      1.0   
66   919.0    119    30/07/2017                      0.0   
67  1023.0    119    30/09/2016                      1.0   
68  1030.0    119    30/09/2017                      0.0   

    MCI relative probability  AD relative probability  ADAS13  \
0                        0.0                      0.0   18.67   
1                        0.0                      0.0   10.67   
2                        0.0                      0.0    8.00   
3               

In [2]:
from tadpole_algorithms.evaluation import evaluate_forecast
eval_set_df = pd.read_csv('data/TADPOLE_D4_corr.csv')

evaluate_forecast(eval_set_df, forecast_df)

[[78  8  0]
 [29 61  2]
 [ 4 12 16]]


/home/tom/Projects/tadpole/tadpole-algorithms/tadpole_algorithms/evaluation/__init__.py:206: RuntimeWarning: divide by zero encountered in true_divide
  adasCoeffs = 1 / (adasEstimUp - adasEstimLo)
/home/tom/Projects/tadpole/tadpole-algorithms/tadpole_algorithms/evaluation/__init__.py:207: RuntimeWarning: invalid value encountered in double_scalars
  adasWES = np.sum(adasCoeffs * np.abs(adasEstim - trueADASFilt)) / np.sum(adasCoeffs)
/home/tom/Projects/tadpole/tadpole-algorithms/tadpole_algorithms/evaluation/__init__.py:209: RuntimeWarning: divide by zero encountered in true_divide
  ventsCoeffs = 1 / (ventriclesEstimUp - ventriclesEstimLo)
/home/tom/Projects/tadpole/tadpole-algorithms/tadpole_algorithms/evaluation/__init__.py:210: RuntimeWarning: invalid value encountered in double_scalars
  ventsWES = np.sum(ventsCoeffs * np.abs(ventriclesEstim - trueVentsFilt)) / np.sum(ventsCoeffs)


(0.7969210797944051,
 0.8814591288452484,
 9.185387415281433,
 9.376404873607639,
 nan,
 nan,
 0.5,
 0.5,
 array([ 9.72841490e+00,  2.65074747e+00,  1.22696353e+01,  1.22696353e+01,
         9.72841490e+00,  8.81330611e-01,  2.05707258e+01,  8.95661133e+00,
         1.51495703e+01,  5.41777762e+00, -1.77279467e+00,  2.76483932e+01,
        -8.88086246e-01,  1.78036956e+01,  1.76603904e+00,  2.04578209e+01,
         2.67636848e+01,  2.39966546e+01,  2.39966546e+01,  1.60342788e+01,
         1.51495703e+01, -3.65511640e+00,  3.11872269e+01,  5.41777762e+00,
         8.95661133e+00,  3.38413522e+01,  3.53545590e+00,  7.95899804e+00,
         1.61245962e+01,  5.70399572e+00,  1.09527046e-01,  1.16107366e+01,
         1.16107366e+01,  3.42255103e+00,  1.39699369e+00,  1.51495703e+01,
         2.76483932e+01,  1.42648619e+01,  4.53306919e+00,  1.16107366e+01,
         1.07260282e+01,  5.30487275e+00,  1.17958312e+01,  1.17958312e+01,
         3.53545590e+00,  3.53545590e+00,  9.72841490e+00,