In [1]:
import pandas as pd
import datetime
from pathlib import Path
from tadpole_algorithms.models import BenchmarkSVM
from tadpole_algorithms.preprocessing.split import split_test_train

data_path = Path("data/TADPOLE_D1_D2.csv")
data_df = pd.read_csv(data_path)

split_fraction = 0.1

train_df, test_df, eval_df = split_test_train(data_df, split_fraction)
test_df = test_df.fillna(0)

model = BenchmarkSVM()
model.train(train_df)

forecast_df = model.predict(test_df)

/home/tom/miniconda3/envs/tadpole/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (471,473,474,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,569,570,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,599,601,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,624,625,626,627,628,629,630,631,632,633,634,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,

In [2]:
from tadpole_algorithms.evaluation import evaluate_forecast

evaluate_forecast(eval_df, forecast_df)

[[36  0  0]
 [ 7 23  1]
 [25  6 22]]


/home/tom/Projects/tadpole/tadpole-algorithms/tadpole_algorithms/evaluation/__init__.py:224: RuntimeWarning: divide by zero encountered in true_divide
  adasCoeffs = 1 / (adasEstimUp - adasEstimLo)
/home/tom/Projects/tadpole/tadpole-algorithms/tadpole_algorithms/evaluation/__init__.py:225: RuntimeWarning: invalid value encountered in double_scalars
  adasWES = np.sum(adasCoeffs * np.abs(adasEstim - trueADASFilt)) / np.sum(adasCoeffs)
/home/tom/Projects/tadpole/tadpole-algorithms/tadpole_algorithms/evaluation/__init__.py:227: RuntimeWarning: divide by zero encountered in true_divide
  ventsCoeffs = 1 / (ventriclesEstimUp - ventriclesEstimLo)
/home/tom/Projects/tadpole/tadpole-algorithms/tadpole_algorithms/evaluation/__init__.py:228: RuntimeWarning: invalid value encountered in double_scalars
  ventsWES = np.sum(ventsCoeffs * np.abs(ventriclesEstim - trueVentsFilt)) / np.sum(ventsCoeffs)


(0.7018608198623304,
 0.862833070693018,
 13.276965746329555,
 42089.25394733456,
 nan,
 nan,
 0.5,
 0.5,
 array([-3.67500201e+00,  1.79075028e+01, -3.67500201e+00, -3.67500201e+00,
        -3.67500201e+00,  8.95474840e+00, -3.67500201e+00,  2.85326861e+01,
         1.82502270e+01,  1.34449238e+01, -3.67500201e+00, -3.67500201e+00,
        -3.67500201e+00,  2.24046573e+01, -3.67500201e+00, -3.67500201e+00,
         1.76389582e+01, -3.67500201e+00, -3.67500201e+00, -3.67500201e+00,
        -3.67500201e+00,  2.68808691e+01, -3.67500201e+00,  7.10067012e+00,
         2.33343122e+01, -3.67500201e+00,  2.68794470e+01, -3.67500201e+00,
        -3.67500201e+00, -3.67500201e+00,  7.24093798e+00,  2.29555747e+01,
        -3.67500201e+00,  2.30721875e+01,  3.18865719e+01, -3.67500201e+00,
        -3.67500201e+00, -3.67500201e+00, -3.67500201e+00,  3.39427853e+01,
         1.33759810e+01,  3.79589792e+01,  9.88601670e+00, -3.67500201e+00,
        -3.67500201e+00,  4.01737023e+01, -3.67500201e+00,