# ECM-EB Example

In [1]:
import pandas as pd
import datetime
from pathlib import Path
from tadpole_algorithms.models import ECMEB

train_set_path = Path("data/TADPOLE_D1_D2.csv")
test_set_path = Path("data/tadpole_test_set.csv")

train_df = pd.read_csv(train_set_path)

test_set_df = pd.read_csv(test_set_path)
test_set_df = test_set_df.fillna(0)

model = ECMEB(confidence_intervals=False)
model.train(train_df)

forecast_df = model.predict(test_set_df)

/home/tom/miniconda3/envs/tadpole2/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3242: DtypeWarning: Columns (471,473,474,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,569,570,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,599,601,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,624,625,626,627,628,629,630,631,632,633,634,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718

In [2]:
from tadpole_algorithms.evaluation import evaluate_forecast
eval_set_df = pd.read_csv('data/TADPOLE_D4_corr.csv')

evaluate_forecast(eval_set_df, forecast_df)

[[ 0 86  0]
 [ 0 92  0]
 [ 0 32  0]]


/home/tom/Projects/tadpole/tadpole-algorithms/tadpole_algorithms/evaluation/__init__.py:206: RuntimeWarning: divide by zero encountered in true_divide
  adasCoeffs = 1 / (adasEstimUp - adasEstimLo)
/home/tom/Projects/tadpole/tadpole-algorithms/tadpole_algorithms/evaluation/__init__.py:207: RuntimeWarning: invalid value encountered in double_scalars
  adasWES = np.sum(adasCoeffs * np.abs(adasEstim - trueADASFilt)) / np.sum(adasCoeffs)
/home/tom/Projects/tadpole/tadpole-algorithms/tadpole_algorithms/evaluation/__init__.py:209: RuntimeWarning: divide by zero encountered in true_divide
  ventsCoeffs = 1 / (ventriclesEstimUp - ventriclesEstimLo)
/home/tom/Projects/tadpole/tadpole-algorithms/tadpole_algorithms/evaluation/__init__.py:210: RuntimeWarning: invalid value encountered in double_scalars
  ventsWES = np.sum(ventsCoeffs * np.abs(ventriclesEstim - trueVentsFilt)) / np.sum(ventsCoeffs)


(0.7827021718065386,
 0.5431315694092063,
 7.333137902207137,
 19.515420174849123,
 nan,
 nan,
 0.5,
 0.5,
 array([19.54522572, 19.54522497, 19.54522663, 19.54522663, 19.54522593,
        19.54522531, 19.54522759, 19.54522541, 19.54522572, 19.54522508,
        19.54522456, 19.54522778, 19.54522496, 19.54522625, 19.54522504,
        19.54522766, 19.54522914, 19.54522754, 19.54522754, 19.54522692,
        19.54522636, 19.54522667, 19.5452279 , 19.54522528, 19.54522641,
        19.54522868, 19.54522505, 19.54522588, 19.54522512, 19.54522223,
        19.54522629, 19.54522659, 19.54522659, 19.54522534, 19.54522283,
        19.54522732, 19.54522865, 19.54522795, 19.5452265 , 19.54522698,
        19.54522682, 19.54522514, 19.54522486, 19.54522486, 19.54522582,
        19.54522582, 19.54522559, 19.54522566, 19.54522609, 19.5452247 ,
        19.54522641, 19.5452217 , 19.54522513, 19.54522667, 19.54522703,
        19.54522703, 19.54522634, 19.54522607, 19.54522644, 19.54522462,
        19.545226