In [1]:
import pandas as pd
import datetime
from pathlib import Path
from tadpole_algorithms.models import SimpleSVM

train_set_path = Path("data/d1d2_short.csv")
test_set_path = Path("data/tadpole_test_set.csv")
test_set_df = pd.read_csv(test_set_path)

test_set_df = test_set_df.fillna(0)

model = SimpleSVM()
model.train(train_set_path)

forecast_df = model.predict(test_set_df)

/home/tom/miniconda3/envs/tadpole2/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3242: DtypeWarning: Columns (471,473,474,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,569,570,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,599,601,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,624,625,626,627,628,629,630,631,632,633,634,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718

In [2]:
from tadpole_algorithms.evaluation import evaluate_forecast
eval_set_df = pd.read_csv('data/TADPOLE_D4_corr.csv')

evaluate_forecast(eval_set_df, forecast_df)

[[78  8  0]
 [29 61  2]
 [ 4 12 16]]


/home/tom/Projects/tadpole/tadpole-algorithms/tadpole_algorithms/evaluation/__init__.py:206: RuntimeWarning: divide by zero encountered in true_divide
  adasCoeffs = 1 / (adasEstimUp - adasEstimLo)
/home/tom/Projects/tadpole/tadpole-algorithms/tadpole_algorithms/evaluation/__init__.py:207: RuntimeWarning: invalid value encountered in double_scalars
  adasWES = np.sum(adasCoeffs * np.abs(adasEstim - trueADASFilt)) / np.sum(adasCoeffs)
/home/tom/Projects/tadpole/tadpole-algorithms/tadpole_algorithms/evaluation/__init__.py:209: RuntimeWarning: divide by zero encountered in true_divide
  ventsCoeffs = 1 / (ventriclesEstimUp - ventriclesEstimLo)
/home/tom/Projects/tadpole/tadpole-algorithms/tadpole_algorithms/evaluation/__init__.py:210: RuntimeWarning: invalid value encountered in double_scalars
  ventsWES = np.sum(ventsCoeffs * np.abs(ventriclesEstim - trueVentsFilt)) / np.sum(ventsCoeffs)


(0.7979256193124368,
 0.8814591288452484,
 9.185387415281433,
 9.376404873607639,
 nan,
 nan,
 0.5,
 0.5,
 array([ 9.72841490e+00,  2.65074747e+00,  1.22696353e+01,  1.22696353e+01,
         9.72841490e+00,  8.81330611e-01,  2.05707258e+01,  8.95661133e+00,
         1.51495703e+01,  5.41777762e+00, -1.77279467e+00,  2.76483932e+01,
        -8.88086246e-01,  1.78036956e+01,  1.76603904e+00,  2.04578209e+01,
         2.67636848e+01,  2.39966546e+01,  2.39966546e+01,  1.60342788e+01,
         1.51495703e+01, -3.65511640e+00,  3.11872269e+01,  5.41777762e+00,
         8.95661133e+00,  3.38413522e+01,  3.53545590e+00,  7.95899804e+00,
         1.61245962e+01,  5.70399572e+00,  1.09527046e-01,  1.16107366e+01,
         1.16107366e+01,  3.42255103e+00,  1.39699369e+00,  1.51495703e+01,
         2.76483932e+01,  1.42648619e+01,  4.53306919e+00,  1.16107366e+01,
         1.07260282e+01,  5.30487275e+00,  1.17958312e+01,  1.17958312e+01,
         3.53545590e+00,  3.53545590e+00,  9.72841490e+00,