In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np
import datetime
from pathlib import Path
from tadpole.models import SimpleSVM
from tadpole.utils import test_train_split

tadpoleD1D2File = Path("/Users/jvdzwaan/data/TADPOLE/data/TADPOLE_D1_D2.csv")

df = pd.read_csv(tadpoleD1D2File)

# remove all rows without
df = df[df["Ventricles"].notnull()]
df = df[df["DXCHANGE"].notnull()]
df = df[df["ADAS13"].notnull()]

train_df, test_df, ground_truth_df = test_train_split(df, 0.1)

model = SimpleSVM()
model.train(train_df)

first_patient_id = test_df['RID'][0]
prediction_orig = model.predict(test_df[test_df['RID'] == first_patient_id], datetime.datetime.now())
truth_orig = ground_truth_df[ground_truth_df['RID'] == first_patient_id]

# evaluate (prediction, truth)

/Users/jvdzwaan/miniconda3/envs/tadpole/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3049: DtypeWarning: Columns (471,473,474,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,569,570,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,599,601,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,624,625,626,627,628,629,630,631,632,633,634,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,71

In [7]:
test_df

RID        PTID VISCODE  SITE  D1  D2 COLPROT ORIGPROT    EXAMDATE  \
0        3  011_S_0003      bl    11   1   0   ADNI1    ADNI1  2005-09-12   
1        3  011_S_0003     m06    11   1   0   ADNI1    ADNI1  2006-03-13   
2        3  011_S_0003     m12    11   1   0   ADNI1    ADNI1  2006-09-12   
3        4  022_S_0004      bl    22   1   0   ADNI1    ADNI1  2005-11-08   
4        4  022_S_0004     m06    22   1   0   ADNI1    ADNI1  2006-05-02   
5        4  022_S_0004     m12    22   1   0   ADNI1    ADNI1  2006-11-14   
6        4  022_S_0004     m18    22   1   0   ADNI1    ADNI1  2007-05-14   
7        5  011_S_0005      bl    11   1   0   ADNI1    ADNI1  2005-09-07   
8        5  011_S_0005     m06    11   1   0   ADNI1    ADNI1  2006-03-09   
9        5  011_S_0005     m24    11   1   0   ADNI1    ADNI1  2007-09-07   
10       6  100_S_0006      bl   100   1   0   ADNI1    ADNI1  2005-11-29   
11       6  100_S_0006     m06   100   1   0   ADNI1    ADNI1  2006-06-01   
12       6  100_S_0006     m12   100   1   0   ADNI1    ADNI1  2006-11-20   
13       6  100_S_0006     m18   100   1   0   ADNI1    ADNI1  2007-05-15   
14       7  022_S_0007      bl    22   1   0   ADNI1    ADNI1  2005-10-06   
15       7  022_S_0007     m06    22   1   0   ADNI1    ADNI1  2006-04-13   
16       8  011_S_0008      bl    11   1   1   ADNI1    ADNI1  2005-09-19   
17      10  011_S_0010      bl    11   1   0   ADNI1    ADNI1  2005-11-10   
18      10  011_S_0010     m06    11   1   0   ADNI1    ADNI1  2006-05-09   
19      10  011_S_0010     m12    11   1   0   ADNI1    ADNI1  2006-11-09   
20      14  022_S_0014      bl    22   1   0   ADNI1    ADNI1  2005-11-04   
21      14  022_S_0014     m06    22   1   0   ADNI1    ADNI1  2006-05-02   
22      14  022_S_0014     m12    22   1   0   ADNI1    ADNI1  2006-11-27   
23      14  022_S_0014     m24    22   1   0   ADNI1    ADNI1  2007-11-27   
24      15  100_S_0015      bl   100   1   1   ADNI1    ADNI1  2005-10-18   
25      15  100_S_0015     m12   100   1   1   ADNI1    ADNI1  2006-10-13   
26      15  100_S_0015     m36   100   1   1   ADNI1    ADNI1  2008-10-28   
27      16  011_S_0016      bl    11   1   0   ADNI1    ADNI1  2005-10-13   
28      16  011_S_0016     m06    11   1   0   ADNI1    ADNI1  2006-04-12   
29      16  011_S_0016     m12    11   1   0   ADNI1    ADNI1  2006-10-11   
...    ...         ...     ...   ...  ..  ..     ...      ...         ...   
4413  5185  127_S_5185      bl   127   1   1   ADNI2    ADNI2  2013-06-07   
4414  5207  072_S_5207     m06    72   1   0   ADNI2    ADNI2  2014-01-20   
4415  4925  130_S_4925     m12   130   1   1   ADNI2    ADNI2  2013-10-14   
4416  5228  127_S_5228      bl   127   1   1   ADNI2    ADNI2  2013-07-11   
4417  5242  019_S_5242     m06    19   1   1   ADNI2    ADNI2  2014-01-14   
4418  5266  127_S_5266      bl   127   1   1   ADNI2    ADNI2  2013-08-15   
4419  5273  135_S_5273      bl   135   1   1   ADNI2    ADNI2  2013-08-20   
4420  4521  002_S_4521     m24     2   1   1   ADNI2    ADNI2  2014-02-27   
4421  5097  041_S_5097     m12    41   1   1   ADNI2    ADNI2  2014-03-17   
4422  4386  032_S_4386     m24    32   1   1   ADNI2    ADNI2  2014-01-23   
4423  4944  052_S_4944     m12    52   1   1   ADNI2    ADNI2  2014-01-31   
4424  2304  067_S_2304     m36    67   1   1   ADNI2   ADNIGO  2014-03-19   
4425  4513  041_S_4513     m24    41   1   1   ADNI2    ADNI2  2014-02-28   
4426  4539  072_S_4539     m24    72   1   1   ADNI2    ADNI2  2014-03-03   
4427  4945  052_S_4945     m12    52   1   1   ADNI2    ADNI2  2014-01-03   
4428  5093  027_S_5093     m12    27   1   1   ADNI2    ADNI2  2014-03-04   
4429  5079  027_S_5079     m12    27   1   1   ADNI2    ADNI2  2014-03-18   
4430  4447  002_S_4447     m24     2   1   1   ADNI2    ADNI2  2014-02-18   
4431  1261  002_S_1261     m84     2   1   1   ADNI2    ADNI1  2014-03-06   
4432  5083  027_S_5083     m12    27   1   1   ADNI2    ADNI2  2014-04-01   
443

In [17]:
ground_truth_df[['RID', 'ADAS13', 'Ventricles','EXAMDATE', 'DXCHANGE']]

RID  ADAS13  Ventricles    EXAMDATE  DXCHANGE
0        3   37.67     97420.0  2007-09-12       3.0
1        4   25.00     45254.0  2008-11-18       2.0
2        5   11.67     41656.0  2008-09-10       1.0
3        6   26.67     46549.0  2008-12-08       2.0
4        8   10.67     18261.0  2006-03-20       1.0
5       10   30.33     35429.0  2007-11-07       3.0
6       14    6.67     53106.0  2008-11-05       1.0
7       16   10.67     18413.0  2008-10-17       1.0
8       19    9.00     22443.0  2008-12-08       1.0
9       22   18.33      7643.0  2007-10-22       4.0
10      29   57.67     66208.0  2008-05-19       3.0
11      35    8.00     25358.0  2008-11-17       1.0
12      38   12.00     31462.0  2006-12-07       2.0
13      40    8.00     46082.0  2009-01-16       1.0
14      42   31.00     68958.0  2011-11-30       3.0
15      45   28.33     72881.0  2006-07-13       2.0
16      47   12.67     69455.0  2008-12-16       1.0
17      51   18.00     36263.0  2008-12-11       2.0
18      53   35.33     85810.0  2007-11-29       3.0
19      60   15.33     32299.0  2007-07-12       2.0
20      67    4.67     39594.0  2008-01-22       1.0
21      70   11.33     34367.0  2007-03-19       1.0
22      72   14.00     33504.0  2012-01-10       1.0
23      76   28.00     36232.0  2008-10-22       3.0
24      77   35.00     50345.0  2008-06-23       3.0
25      80   19.00     19642.0  2007-01-09       2.0
26      81    8.00     48305.0  2010-03-11       1.0
27      83   37.00     51736.0  2008-01-31       3.0
28      84   27.00     34341.0  2008-01-22       3.0
29      87   27.67     70917.0  2007-08-01       2.0
...    ...     ...         ...         ...       ...
1323  5228    5.00     29650.0  2015-07-07       1.0
1324  5234   11.00    103622.0  2015-07-08       4.0
1325  5236   11.00     28245.0  2015-07-24       1.0
1326  5242    2.00     18294.0  2015-08-05       1.0
1327  5243   10.00     23797.0  2015-08-31       1.0
1328  5244    2.00     18070.0  2015-08-05       1.0
1329  5253    8.00     23964.0  2015-07-22       1.0
1330  5256    9.00     24258.0  2015-09-08       1.0
1331  5259    9.00     16033.0  2015-08-28       1.0
1332  5266    3.00     36056.0  2015-08-06       1.0
1333  5269    6.00     19975.0  2015-09-01       1.0
1334  5273    9.00     56317.0  2015-08-26       2.0
1335  5277   10.00     29814.0  2015-08-31       1.0
1336  5290    7.00     12472.0  2015-10-01       1.0
1337  5292    5.00     17160.0  2015-11-19       1.0
1338  2407   16.00     25845.0  2015-12-01       2.0
1339  4360    1.00     20682.0  2015-12-22       2.0
1340  5263   21.00     49475.0  2016-01-05       1.0
1341  4176    9.00     35158.0  2016-01-04       1.0
1342  4179   12.00     67531.0  2016-01-04       1.0
1343   824   13.00     30778.0  2016-01-12       1.0
1344  4311   10.00     37990.0  2016-01-14       2.0
1345  4312   10.00     26719.0  2016-01-13       2.0
1346  4410    5.00     17990.0  2016-01-13       1.0
1347  4386    3.00     28550.0  2016-02-02       1.0
1348  4404   20.00     35534.0  2016-02-03       2.0
1349  4324   39.00     83182.0  2016-02-10       3.0
1350  4446   12.00     17803.0  2016-02-11       2.0
1351  4488    8.00     26809.0  2016-02-23       1.0
1352  4513    2.00     39519.0  2016-03-04       7.0

[1353 rows x 5 columns]

* CognitiveAssessmentDate = ExamDate (source: https://github.com/tadpole-share/TADPOLE-eval/blob/c8d4e241bc143b858d9b8237aab92417d3e871e2/evaluation/makeLeaderboardDataset.py#L159)
* ScanDate = ExamDate (source: https://github.com/tadpole-share/TADPOLE-eval/blob/c8d4e241bc143b858d9b8237aab92417d3e871e2/evaluation/makeLeaderboardDataset.py#L162)
* Diagnosis = DXCHANGE with mapping (source: https://github.com/tadpole-share/TADPOLE-eval/blob/c8d4e241bc143b858d9b8237aab92417d3e871e2/evaluation/makeLeaderboardDataset.py#L160 and line 169-170)
* RID = Patient id (what is it used for? Why must it be set?)

In [3]:
from tadpole.transformations import get_diagnosis

# make copies so we don't have to train all the time
prediction = prediction_orig.copy()
truth = truth_orig.copy()

# The Forecast date has to be a string
p = pd.DataFrame(prediction)
p['Forecast Date'] = p['Forecast Date'].astype(str)
print(p.dtypes)

# Add expected columns
truth['CognitiveAssessmentDate'] = truth['EXAMDATE']
truth['ScanDate'] = truth['EXAMDATE']

truth['Diagnosis'] = get_diagnosis(truth)

AD relative probability        float64
ADAS13                         float64
ADAS13 50% CI lower            float64
ADAS13 50% CI upper            float64
CN relative probability        float64
Diagnosis                      float64
Forecast Date                   object
MCI relative probability       float64
RID                              int64
Ventricles_ICV                 float64
Ventricles_ICV 50% CI lower    float64
Ventricles_ICV 50% CI upper    float64
dtype: object


In [ ]:
prediction

In [ ]:
for c in ground_truth_df.columns:
    print(c)

In [4]:
def outcomes_equal(result1, result2):
    """Method that checks whether two evaluation outcomes are equal.
    """
    for i1, i2 in zip(result1, result2):
        if isinstance(i1, pd.Series):
            r = i1.equals(i2)
        else:
            r = i1 == i1 or np.isnan(i1) and np.isnan(i2)

        if not r:
            return False
    return True

In [9]:
from evaluation import evalOneSubmissionExtended, simpleEvalOneSubmissionExtended

p = pd.DataFrame(prediction)
p['Forecast Date'] = p['Forecast Date'].astype(str)

res1 = evalOneSubmissionExtended.evalOneSub(truth.copy(), p.copy())
res2 = simpleEvalOneSubmissionExtended.evalOneSub(truth.copy(), p.copy())
                           
assert outcomes_equal(res1, res2)

a_value 0 0 0
a_value 0 0 0
a_value 0 1 0
a_value 1 0 1
a_value 0 1 0
a_value 1 0 1
[[0 0 0]
 [0 0 0]
 [0 0 1]]
Number of subjects: 1
a_value 0 0 0
a_value 0 0 0
a_value 0 1 0
a_value 1 0 1
a_value 0 1 0
a_value 1 0 1
[[0 0 0]
 [0 0 0]
 [0 0 1]]


In [6]:
res1

(0.0,
 0.6666666666666666,
 0.6225826460276949,
 97419.95826182756,
 0.6225826460276949,
 97419.95826182756,
 0.5,
 0.5,
 array([37.04741735]),
 0    37.67
 Name: ADAS13, dtype: float64)

In [7]:
res2

(0.0,
 0.6666666666666666,
 0.6225826460276949,
 97419.95826182756,
 0.6225826460276949,
 97419.95826182756,
 0.5,
 0.5,
 array([37.04741735]),
 0    37.67
 Name: ADAS13, dtype: float64)

In [ ]:
for i, (i1, i2) in enumerate(zip(res1, res2)):
    print(i, i1==i2, type(i1))

In [ ]:
import numpy as np

np.nan == np.nan

The evaluation code expects as input:

* `d4Df`: Pandas data frame containing the D4 dataset
  * 
  * Required fields in the DataFrame:
    * 
* `forecastDf`: Pandas data frame containing user forecasts for D2 subjects.
  * Predictions
  * Required fields in the DataFrame:
    * Diagnosis
    * ADAS13
    * Ventricles_ICV
    * Forecast Date (string in the format `%Y-%m`)
    * RID: Patient ID
    * CN relative probability
    * MCI relative probability
    * AD relative probability
    * ADAS13 50% CI lower
    * ADAS13 50% CI upper
    * Ventricles_ICV 50% CI lower
    * Ventricles_ICV 50% CI upper

In [ ]:
import datetime

a = datetime.datetime.now()
b = a.strftime('%Y-%m')
type(b)

In [ ]:
datetime.datetime.strptime(b, '%Y-%m')

In [ ]:
def average_time_between_visits(df):
    df1 = df[['RID', 'EXAMDATE']].copy()
    df1 = df1.sort_values(by=['RID', 'EXAMDATE'])
    df1['EXAMDATE'] = df1['EXAMDATE'].map(lambda x: datetime.datetime.strptime(x, '%Y-%m-%d'))
    # Get future value from each row's next row
    df1["Future_EXAMDATE"] = df1['EXAMDATE'].shift(-1)
    # Drop each last row per patient
    df1 = df1.drop(df1.groupby('RID').tail(1).index.values)
    return (df1['Future_EXAMDATE']-df1['EXAMDATE']).mean()


In [ ]:
average_time_between_visits(df)

In [ ]:
truth